### ISSUE TITLE
[Deploy] CI/CD 파이프라인 구축

### ISSUE THREAD

**Issue by eojinny** [Bid-5th-umc/Backend#1]
## 👛 Feature Issue
무중단 배포 
## 👛 작업 브랜치
- dev

## 📝 To-do
- [ ] script 파일 작성
- [ ] docker-compose.yml 작성
- [ ] ci.yml 작성
- [ ] nginx.conf 수정
- [ ] application.yml 작성
